/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantId' : bigint,
  'imageUrl' : [] | [ExternalBlob],
  'category' : string,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : bigint,
  'isPaid' : boolean,
  'restaurantId' : bigint,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
  'deliveryAgentId' : [] | [Principal],
  'subtotal' : bigint,
}
export interface OrderItem {
  'foodItemId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'picked_up' : null } |
  { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'delivered' : null } |
  { 'accepted' : null } |
  { 'ready_for_pickup' : null };
export type PaymentMethod = { 'cash' : null } |
  { 'online' : null };
export interface Restaurant {
  'id' : bigint,
  'isApproved' : boolean,
  'ownerId' : Principal,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'cuisineType' : string,
  'description' : string,
  'address' : string,
  'isSuspended' : boolean,
  'phone' : string,
}
export type Role = { 'customer' : null } |
  { 'delivery_agent' : null } |
  { 'restaurant_owner' : null };
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'isVerified' : boolean,
  'isSuspended' : boolean,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrder' : ActorMethod<[bigint, boolean], undefined>,
  'activateUser' : ActorMethod<[Principal], undefined>,
  'addMenuItem' : ActorMethod<
    [bigint, string, string, bigint, string, [] | [ExternalBlob]],
    bigint
  >,
  'approveRestaurant' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDeliveryAgent' : ActorMethod<[bigint], undefined>,
  'cancelOrder' : ActorMethod<[bigint], undefined>,
  'createCoupon' : ActorMethod<[string, bigint, bigint, bigint], undefined>,
  'createRestaurant' : ActorMethod<
    [string, string, string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'ordersByStatus' : Array<[OrderStatus, bigint]>,
      'totalOrders' : bigint,
      'totalRevenue' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeliveryAgentEarnings' : ActorMethod<[Principal], bigint>,
  'getMenuByRestaurant' : ActorMethod<[bigint], Array<MenuItem>>,
  'getMyRestaurant' : ActorMethod<[], [] | [Restaurant]>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersByDeliveryAgent' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersByRestaurant' : ActorMethod<[bigint], Array<Order>>,
  'getPlatformRevenue' : ActorMethod<[], bigint>,
  'getRestaurant' : ActorMethod<[bigint], [] | [Restaurant]>,
  'getRestaurantEarnings' : ActorMethod<[bigint], bigint>,
  'getTopFoodItems' : ActorMethod<[bigint], Array<[bigint, bigint]>>,
  'getTopRestaurants' : ActorMethod<[bigint], Array<[bigint, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsersByRole' : ActorMethod<[Role], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [bigint, Array<OrderItem>, string, PaymentMethod, [] | [string]],
    bigint
  >,
  'registerUser' : ActorMethod<[string, string, Role], undefined>,
  'rejectRestaurant' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'suspendRestaurant' : ActorMethod<[bigint], undefined>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'updateMenuItem' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [boolean],
    ],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateRestaurant' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'validateCoupon' : ActorMethod<[string], boolean>,
  'verifyDeliveryAgent' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];