/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'picked_up' : IDL.Null,
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
  'ready_for_pickup' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'online' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'foodItemId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : IDL.Nat,
  'isPaid' : IDL.Bool,
  'restaurantId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'deliveryAgentId' : IDL.Opt(IDL.Principal),
  'subtotal' : IDL.Nat,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'ownerId' : IDL.Principal,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'isSuspended' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Role = IDL.Variant({
  'customer' : IDL.Null,
  'delivery_agent' : IDL.Null,
  'restaurant_owner' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'isVerified' : IDL.Bool,
  'isSuspended' : IDL.Bool,
  'phone' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantId' : IDL.Nat,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptOrder' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'activateUser' : IDL.Func([IDL.Principal], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'approveRestaurant' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDeliveryAgent' : IDL.Func([IDL.Nat], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [], []),
  'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Int], [], []),
  'createRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'ordersByStatus' : IDL.Vec(IDL.Tuple(OrderStatus, IDL.Nat)),
          'totalOrders' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeliveryAgentEarnings' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getMenuByRestaurant' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
  'getMyRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
  'getOrdersByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersByDeliveryAgent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersByRestaurant' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getPlatformRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'getRestaurant' : IDL.Func([IDL.Nat], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantEarnings' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTopFoodItems' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getTopRestaurants' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersByRole' : IDL.Func([Role], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(OrderItem), IDL.Text, PaymentMethod, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [], []),
  'rejectRestaurant' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'suspendRestaurant' : IDL.Func([IDL.Nat], [], []),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'updateMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateRestaurant' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyDeliveryAgent' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'picked_up' : IDL.Null,
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
    'ready_for_pickup' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'cash' : IDL.Null, 'online' : IDL.Null });
  const OrderItem = IDL.Record({
    'foodItemId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'deliveryFee' : IDL.Nat,
    'isPaid' : IDL.Bool,
    'restaurantId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'deliveryAgentId' : IDL.Opt(IDL.Principal),
    'subtotal' : IDL.Nat,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'ownerId' : IDL.Principal,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'isSuspended' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Role = IDL.Variant({
    'customer' : IDL.Null,
    'delivery_agent' : IDL.Null,
    'restaurant_owner' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'isVerified' : IDL.Bool,
    'isSuspended' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantId' : IDL.Nat,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptOrder' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'activateUser' : IDL.Func([IDL.Principal], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'approveRestaurant' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDeliveryAgent' : IDL.Func([IDL.Nat], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [], []),
    'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Int], [], []),
    'createRestaurant' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'ordersByStatus' : IDL.Vec(IDL.Tuple(OrderStatus, IDL.Nat)),
            'totalOrders' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeliveryAgentEarnings' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getMenuByRestaurant' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
    'getMyRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
    'getOrdersByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersByDeliveryAgent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersByRestaurant' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getPlatformRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'getRestaurant' : IDL.Func([IDL.Nat], [IDL.Opt(Restaurant)], ['query']),
    'getRestaurantEarnings' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTopFoodItems' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getTopRestaurants' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersByRole' : IDL.Func([Role], [IDL.Vec(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(OrderItem),
          IDL.Text,
          PaymentMethod,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [], []),
    'rejectRestaurant' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'suspendRestaurant' : IDL.Func([IDL.Nat], [], []),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateRestaurant' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyDeliveryAgent' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };